name: NEKO

title: NEKO
description: null

version: v0.2

baseurl: ""
permalink: /:slug/
logo: /assets/logo.png

theme: jekyll-theme-hacker

plugins:
  - jekyll-redirect-from

collections:
  urls:
    output: false
    permalink: /:slug

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - _urls

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
